---
title: "COVID-19 Presidential Debates (1)"
author: "David Jackson"
date: "9/29/2020"
output: 
  html_document: 
    fig_width: 9
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
library(ggplot2)
library(scales)
library(plotly)
theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))

```

```{r}
df <- read.csv("./COVID-19.csv")
df$Ymd <- as.Date(df$Ymd,format="%m-%d-%Y")
df <- df[order(df$Ymd,decreasing = TRUE),]
US <- subset(df,geoId =="US")
no_us <- subset(df,geoId !="US")
```
```{r}
worldCases <- aggregate(cases~Ymd,df,FUN=sum)
worldDeaths <- aggregate(deaths~Ymd,df,FUN=sum)
worldCases$cumCases <- cumsum(worldCases$cases)
worldDeaths$cumdeaths <- cumsum(worldDeaths$deaths)
```
```{r}
no_Cases <- aggregate(cases~Ymd,no_us,FUN=sum)
no_Deaths <- aggregate(deaths~Ymd,no_us,FUN=sum)

no_Cases$cumCases <- cumsum(no_Cases$cases)
no_Deaths$cumdeaths <- cumsum(no_Deaths$deaths)

```

### Plot of Cumulative COID-19 Cases and Deaths for the World

```{r}
ggplot(worldCases) +
  geom_line(aes(x=Ymd,y=cumCases,col="World"))  +
  geom_line(data=no_Cases,aes(x=Ymd,y=cumCases,col="NO US")) +
  labs(title="World (incuding US) Cumulative Covid19 Cases")

ggplot(worldDeaths) +
  geom_line(aes(x=Ymd,y=cumdeaths,col="World"))  +
  geom_line(data=no_Deaths,aes(x=Ymd,y=cumdeaths,col="NO US")) +
  labs(title="World (incuding US) Cumulative Covid19 Deaths")
```

### Plot of Daily COID-19 Cases and Deaths for the World

```{r}
ggplot(worldCases,aes(x=Ymd,y=cases)) +
  geom_line() + geom_smooth(aes(x=Ymd,y=cases),span=0.25) +
  labs(title="World (incuding US) Daily Covid19 Cases")

ggplot(worldDeaths,aes(x=Ymd,y=deaths)) +
  geom_line() + geom_smooth(aes(x=Ymd,y=deaths),span=0.25) +
  labs(title="World (incuding US) Daily Covid19 Deaths")
```

### Plot of Daily COID-19 Cases and Deaths for the World

```{r}
ggplot(no_Cases,aes(x=Ymd,y=cases)) +
  geom_line()+
  labs(title="World (without US) Daily Covid19 Cases") +
  geom_smooth(aes(x=Ymd,y=cases),span=0.25) 
  
ggplot(no_Deaths,aes(x=Ymd,y=deaths)) +
  geom_line()+
  labs(title="World (without US) Daily Covid19 Cases") +
  geom_smooth(aes(x=Ymd,y=deaths),span=0.25) 
 

```

### Plot of Combined with and with out US COID-19 Cases and Deaths for the World

```{r}
ggplot() + geom_line(data=worldCases,aes(x=Ymd,y=cases,col="World")) +
  geom_line(data=no_Cases,aes(x=Ymd,y=cases,col="NO US")) + 
  labs(title="Comparing WorldCases with and Without the US")

ggplot() + geom_line(data=worldDeaths,aes(x=Ymd,y=deaths,col="World")) +
  geom_line(data=no_Deaths,aes(x=Ymd,y=deaths,col="NO US")) + 
  labs(title="Comparing World Deaths with and Without the US")
```





### Plot of Daily COID-19 Cases and Deaths for the US

```{r}
ggplot(US,aes(x=Ymd,y=cases)) +
  geom_line()+
  labs(title="US  Daily Covid19 Cases") +
  geom_smooth(aes(x=Ymd,y=cases),span=0.25) 
  
ggplot(US,aes(x=Ymd,y=deaths)) +
  geom_line()+
  labs(title="US Daily Covid19 Deaths") +
  geom_smooth(aes(x=Ymd,y=deaths),span=0.25) 
```
```{r}
ggplot() + geom_smooth(data=worldCases,aes(x=Ymd,y=cases,col="World")) +
  geom_smooth(data=no_Cases,aes(x=Ymd,y=cases,col="NO US")) + 
  labs(title="Comparing Lowss/Loess World Cases with and Without the US")

ggplot() + geom_smooth(data=worldDeaths,aes(x=Ymd,y=deaths,col="World")) +
  geom_smooth(data=no_Deaths,aes(x=Ymd,y=deaths,col="NO US")) + 
  labs(title="Comparing Lowss/Loess World Deaths with and Without the US")
```

 